markdown: kramdown
highlighter: pygments

production_url: '/squeak-actors'

defaults:
  -
    scope:
      path: ""
    values:
      layout: page

title: Squeak Actors

author:
  twitter: 'leastfixedpoint'
  fullname: 'Tony Garnock-Jones'
  gravatar: 'tonyg@leastfixedpoint.com'
  email: 'tonyg@leastfixedpoint.com'

links:
  squeaksource: 'http://www.squeaksource.com/Actors.html'
  github: 'https://github.com/tonyg/squeak-actors'
  documentation: 'http://tonyg.github.io/squeak-actors'

squeak_updatenumber: 17738

contact_email: 'tonyg@leastfixedpoint.com'
